### PR TITLE
Log train metrics into Weights & Biases for Object Detection task

### PR DESCRIPTION
**Pull request by parambharat**
This PR adds the ability to log training metrics for object detection into Weights & Biases.
Here's an example [dashboard](https://wandb.ai/parambharat/yolov7/runs/3hlqu5cm?workspace=user-parambharat) of fine-tuning the faster_rcnn_R_101_FPN_3x detection model from detectron2 [model zoo](https://github.com/facebookresearch/detectron2/blob/main/MODEL_ZOO.md).

### CODE REVIEW

**Comment by jinfagang** [comment]
@parambharat  Thanks for the contribution! Can u further helps on:

1). It can be good if wandadb is optional (pepople should able to train without this lib installed, and when training, there better have an option to enable, default is disable);
2). I would suggest move all wandadb related files to `wandadb` folder or inside utils, don't place loggers out there since we have too many loggers.

**Comment by parambharat** [comment]
Hi @jinfagang , Thanks for the quick review and comment. 
1. I have moved the `wandb` logger to a new module under `utils` as recommended.  I'm keeping this as a module since this allows us to add new features for semantic segmentation and other functionalities in the upcoming PRs for these.
2. `wandb` is already optional. I've tested the code with and without wandb installation. Notice that the imports are all lazy and that we check for installation before import and use of wandb features.

**Comment by parambharat** [comment]
Hi @jinfagang , just following up. Did you get a chance to review the PR after the changes you recommended were made. Let me know if you want any additional changes/Information. I'll build the logger for the other tasks based on your recommendations.

**Comment by jinfagang** [comment]
@parambharat Hi, I saw that `train_det.py` were all changed, this would make others have merge conflicts when pull, can u make it only changed the line you needed for import wandb logger?

**Pull request merged**
